# Generated by Django 4.1.4 on 2023-02-22 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_alter_post_image_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upvote',
            field=models.ManyToManyField(related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
