# Generated by Django 4.1.4 on 2023-02-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_post_upvote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='like',
        ),
    ]
