# Generated by Django 4.1.4 on 2023-03-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_comments_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('in_active', 'in_active')], default='active', max_length=200),
        ),
    ]
