# Generated by Django 4.1.4 on 2023-03-11 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_status_userprofile_in_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='in_active',
            new_name='is_active',
        ),
    ]
